<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260407104137 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE chat DROP FOREIGN KEY `IdProject`');
        $this->addSql('ALTER TABLE chat DROP FOREIGN KEY `IdUser`');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY `idChat`');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY `idSender`');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY `id_task`');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY `id_user`');
        $this->addSql('DROP TABLE chat');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE payment');
        $this->addSql('ALTER TABLE admin DROP FOREIGN KEY `User`');
        $this->addSql('ALTER TABLE admin DROP FOREIGN KEY `User`');
        $this->addSql('ALTER TABLE admin ADD CONSTRAINT FK_880E0D76FE6E88D7 FOREIGN KEY (idUser) REFERENCES `user` (idUser) ON DELETE CASCADE');
        $this->addSql('DROP INDEX user ON admin');
        $this->addSql('CREATE INDEX IDX_880E0D76FE6E88D7 ON admin (idUser)');
        $this->addSql('ALTER TABLE admin ADD CONSTRAINT `User` FOREIGN KEY (idUser) REFERENCES user (idUser) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY `fk_application_freelancer`');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY `fk_application_project`');
        $this->addSql('DROP INDEX fk_application_project ON application');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY `fk_application_freelancer`');
        $this->addSql('ALTER TABLE application MODIFY idApplication INT NOT NULL');
        $this->addSql('ALTER TABLE application CHANGE status status VARCHAR(255) NOT NULL, CHANGE cover_letter cover_letter LONGTEXT NOT NULL, CHANGE applied_at applied_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL, CHANGE idApplication id INT AUTO_INCREMENT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC18545BDF5 FOREIGN KEY (freelancer_id) REFERENCES freelancer (idFreelancer)');
        $this->addSql('DROP INDEX fk_application_freelancer ON application');
        $this->addSql('CREATE INDEX IDX_A45BDDC18545BDF5 ON application (freelancer_id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT `fk_application_freelancer` FOREIGN KEY (freelancer_id) REFERENCES freelancer (idFreelancer) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY `fk_client_user`');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY `fk_client_user`');
        $this->addSql('ALTER TABLE client DROP industry');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C74404555FD86D04 FOREIGN KEY (userID) REFERENCES `user` (idUser) ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C74404554FBF094F ON client (company)');
        $this->addSql('DROP INDEX userid ON client');
        $this->addSql('CREATE INDEX IDX_C74404555FD86D04 ON client (userID)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT `fk_client_user` FOREIGN KEY (userID) REFERENCES user (idUser) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY `contract_ibfk_1`');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY `fk_contract_freelancer`');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY `fk_contract_template`');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY `idClient`');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY `idPayment`');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY `id_project`');
        $this->addSql('DROP INDEX fk_contract_freelancer ON contract');
        $this->addSql('DROP INDEX idClient ON contract');
        $this->addSql('DROP INDEX fk_contract_template ON contract');
        $this->addSql('DROP INDEX idPayment ON contract');
        $this->addSql('DROP INDEX id_project ON contract');
        $this->addSql('ALTER TABLE contract ADD title VARCHAR(255) NOT NULL, ADD content LONGTEXT NOT NULL, ADD clientSignature DATETIME DEFAULT NULL, ADD clientSignatureImage LONGTEXT DEFAULT NULL, ADD freelancerSignature DATETIME DEFAULT NULL, ADD freelancerSignatureImage LONGTEXT DEFAULT NULL, ADD createdAt DATETIME NOT NULL, ADD updatedAt DATETIME NOT NULL, ADD idContractTemplate INT NOT NULL, ADD idClient INT NOT NULL, ADD idFreelancer INT NOT NULL, DROP projectID, DROP PaymentID, DROP ClientID, DROP Type, DROP templateID, DROP freelancerID, DROP clientSignatureDate, DROP freelancerSignatureDate, CHANGE startDate startDate DATE NOT NULL, CHANGE EndDate endDate DATE NOT NULL, CHANGE status status VARCHAR(20) NOT NULL, CHANGE amount amount NUMERIC(10, 2) NOT NULL');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F285991B5BE79 FOREIGN KEY (idContractTemplate) REFERENCES contract_template (idContractTemplate)');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F2859A455ACCF FOREIGN KEY (idClient) REFERENCES client (idClient)');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F2859CEDACF02 FOREIGN KEY (idFreelancer) REFERENCES freelancer (idFreelancer)');
        $this->addSql('CREATE INDEX IDX_E98F285991B5BE79 ON contract (idContractTemplate)');
        $this->addSql('CREATE INDEX IDX_E98F2859A455ACCF ON contract (idClient)');
        $this->addSql('CREATE INDEX IDX_E98F2859CEDACF02 ON contract (idFreelancer)');
        $this->addSql('DROP INDEX templateName ON contract_template');
        $this->addSql('DROP INDEX idx_templateName ON contract_template');
        $this->addSql('ALTER TABLE contract_template MODIFY idTemplate INT NOT NULL');
        $this->addSql('ALTER TABLE contract_template ADD contractType VARCHAR(50) NOT NULL, ADD createdAt DATETIME NOT NULL, ADD updatedAt DATETIME NOT NULL, DROP createdDate, DROP updatedDate, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE idTemplate idContractTemplate INT AUTO_INCREMENT NOT NULL, CHANGE templateName title VARCHAR(255) NOT NULL, CHANGE templateContent content LONGTEXT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idContractTemplate)');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY `fk_evaluated`');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY `fk_evaluator`');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY `fk_project`');
        $this->addSql('DROP INDEX fk_project ON evaluation');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY `fk_evaluated`');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY `fk_evaluator`');
        $this->addSql('ALTER TABLE evaluation MODIFY idEvaluation INT NOT NULL');
        $this->addSql('ALTER TABLE evaluation CHANGE project_id project_id INT DEFAULT NULL, CHANGE comment comment LONGTEXT NOT NULL, CHANGE type type VARCHAR(255) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL, CHANGE idEvaluation id INT AUTO_INCREMENT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A57543575BE2 FOREIGN KEY (evaluator_id) REFERENCES `user` (idUser)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A5757C954B00 FOREIGN KEY (evaluated_id) REFERENCES `user` (idUser)');
        $this->addSql('DROP INDEX fk_evaluator ON evaluation');
        $this->addSql('CREATE INDEX IDX_1323A57543575BE2 ON evaluation (evaluator_id)');
        $this->addSql('DROP INDEX fk_evaluated ON evaluation');
        $this->addSql('CREATE INDEX IDX_1323A5757C954B00 ON evaluation (evaluated_id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT `fk_evaluated` FOREIGN KEY (evaluated_id) REFERENCES user (idUser) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT `fk_evaluator` FOREIGN KEY (evaluator_id) REFERENCES user (idUser) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE freelancer DROP FOREIGN KEY `fk_freelancer_portfolio`');
        $this->addSql('ALTER TABLE freelancer DROP FOREIGN KEY `fk_freelancer_task`');
        $this->addSql('DROP INDEX PortfolioID ON freelancer');
        $this->addSql('DROP INDEX ApplicationID ON freelancer');
        $this->addSql('DROP INDEX TaskID ON freelancer');
        $this->addSql('ALTER TABLE freelancer DROP idApplication, DROP idPortfolio, CHANGE skills skills VARCHAR(255) NOT NULL, CHANGE verificationStatus verificationStatus VARCHAR(20) NOT NULL, CHANGE status status VARCHAR(20) NOT NULL, CHANGE idTask idTask INT DEFAULT NULL');
        $this->addSql('ALTER TABLE freelancer ADD CONSTRAINT FK_4C2ED1E8FE6E88D7 FOREIGN KEY (idUser) REFERENCES `user` (idUser) ON DELETE CASCADE');
        $this->addSql('DROP INDEX userid ON freelancer');
        $this->addSql('CREATE INDEX IDX_4C2ED1E8FE6E88D7 ON freelancer (idUser)');
        $this->addSql('ALTER TABLE freelancer_forum_comment DROP FOREIGN KEY `freelancerID`');
        $this->addSql('ALTER TABLE freelancer_forum_comment DROP FOREIGN KEY `postID`');
        $this->addSql('DROP INDEX postID ON freelancer_forum_comment');
        $this->addSql('DROP INDEX freelancerID ON freelancer_forum_comment');
        $this->addSql('ALTER TABLE freelancer_forum_comment CHANGE post_id post_id INT NOT NULL, CHANGE comment_text comment_text LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE freelancer_forum_post DROP FOREIGN KEY `freelancerPOST`');
        $this->addSql('DROP INDEX freelancerPOST ON freelancer_forum_post');
        $this->addSql('ALTER TABLE freelancer_forum_post ADD gif_url VARCHAR(500) DEFAULT NULL, ADD category VARCHAR(50) NOT NULL, CHANGE content content LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE views views INT NOT NULL');
        $this->addSql('ALTER TABLE freelancer_forum_reaction DROP FOREIGN KEY `freelancerREACT`');
        $this->addSql('ALTER TABLE freelancer_forum_reaction DROP FOREIGN KEY `postREACT`');
        $this->addSql('DROP INDEX freelancerREACT ON freelancer_forum_reaction');
        $this->addSql('DROP INDEX postREACT ON freelancer_forum_reaction');
        $this->addSql('ALTER TABLE freelancer_forum_reaction CHANGE reaction_type reaction_type VARCHAR(20) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX user_post_unique ON freelancer_forum_reaction (freelancer_id, post_id)');
        $this->addSql('ALTER TABLE portfolio DROP FOREIGN KEY `fk_portfolio_freelancer`');
        $this->addSql('ALTER TABLE portfolio DROP FOREIGN KEY `fk_portfolio_freelancer`');
        $this->addSql('ALTER TABLE portfolio CHANGE created_At created_At DATETIME NOT NULL');
        $this->addSql('ALTER TABLE portfolio ADD CONSTRAINT FK_A9ED10624DCE947A FOREIGN KEY (freelancerId) REFERENCES freelancer (idFreelancer) ON DELETE CASCADE');
        $this->addSql('DROP INDEX freelancer ON portfolio');
        $this->addSql('CREATE INDEX IDX_A9ED10624DCE947A ON portfolio (freelancerId)');
        $this->addSql('ALTER TABLE portfolio ADD CONSTRAINT `fk_portfolio_freelancer` FOREIGN KEY (freelancerId) REFERENCES freelancer (idFreelancer) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE portfolioitem DROP FOREIGN KEY `fk_portfolioitem_portfolio`');
        $this->addSql('ALTER TABLE portfolioitem DROP FOREIGN KEY `fk_portfolioitem_portfolio`');
        $this->addSql('ALTER TABLE portfolioitem CHANGE title title VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(500) DEFAULT NULL, CHANGE technologies technologies VARCHAR(500) DEFAULT NULL, CHANGE imageUrl imageUrl VARCHAR(500) DEFAULT NULL, CHANGE projectUrl projectUrl VARCHAR(255) DEFAULT NULL, CHANGE githubUrl githubUrl VARCHAR(255) DEFAULT NULL, CHANGE created_At created_At DATETIME NOT NULL');
        $this->addSql('ALTER TABLE portfolioitem ADD CONSTRAINT FK_D6C82F0B55073B34 FOREIGN KEY (idPortfolio) REFERENCES portfolio (idPortfolio) ON DELETE CASCADE');
        $this->addSql('DROP INDEX portfolio ON portfolioitem');
        $this->addSql('CREATE INDEX IDX_D6C82F0B55073B34 ON portfolioitem (idPortfolio)');
        $this->addSql('ALTER TABLE portfolioitem ADD CONSTRAINT `fk_portfolioitem_portfolio` FOREIGN KEY (idPortfolio) REFERENCES portfolio (idPortfolio) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY `id_client`');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY `id_client`');
        $this->addSql('ALTER TABLE project ADD freelancerIDD INT DEFAULT NULL, CHANGE status status VARCHAR(12) NOT NULL');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE2804AB20 FOREIGN KEY (ClientID) REFERENCES client (idClient)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE76A0B4B2 FOREIGN KEY (freelancerID) REFERENCES freelancer (idFreelancer)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE86AA1810 FOREIGN KEY (freelancerIDD) REFERENCES freelancer (idFreelancer)');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE76A0B4B2 ON project (freelancerID)');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE86AA1810 ON project (freelancerIDD)');
        $this->addSql('DROP INDEX id_client ON project');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE2804AB20 ON project (ClientID)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT `id_client` FOREIGN KEY (ClientID) REFERENCES client (idClient) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY `task_ibfk_1`');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY `task_ibfk_1`');
        $this->addSql('ALTER TABLE task CHANGE deadline deadline DATETIME NOT NULL, CHANGE TaskStatus TaskStatus VARCHAR(50) NOT NULL, CHANGE dateAssign dateAssign DATETIME NOT NULL, CHANGE priority priority VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB253F0ABB1C FOREIGN KEY (idProject) REFERENCES project (idProject)');
        $this->addSql('DROP INDEX projectid ON task');
        $this->addSql('CREATE INDEX IDX_527EDB253F0ABB1C ON task (idProject)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT `task_ibfk_1` FOREIGN KEY (idProject) REFERENCES project (idProject) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON user (email)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chat (idChat INT AUTO_INCREMENT NOT NULL, created_At DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, status TINYINT NOT NULL, projectID INT NOT NULL, userID INT NOT NULL, INDEX IdUser (userID), INDEX IdProject (projectID), PRIMARY KEY (idChat)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE message (idMessage INT AUTO_INCREMENT NOT NULL, content VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, sentDate DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, seen TINYINT NOT NULL, ChatID INT NOT NULL, SenderID INT NOT NULL, INDEX idChat (ChatID), INDEX idSender (SenderID), PRIMARY KEY (idMessage)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE payment (idPayment INT AUTO_INCREMENT NOT NULL, amount DOUBLE PRECISION NOT NULL, datePayment DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, paymentStatus LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, userID INT NOT NULL, taskID INT NOT NULL, INDEX id_user (userID), INDEX id_task (taskID), PRIMARY KEY (idPayment)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE chat ADD CONSTRAINT `IdProject` FOREIGN KEY (projectID) REFERENCES project (idProject) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat ADD CONSTRAINT `IdUser` FOREIGN KEY (userID) REFERENCES user (idUser) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT `idChat` FOREIGN KEY (ChatID) REFERENCES chat (idChat) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT `idSender` FOREIGN KEY (SenderID) REFERENCES user (idUser) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT `id_task` FOREIGN KEY (taskID) REFERENCES task (idTask) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT `id_user` FOREIGN KEY (userID) REFERENCES user (idUser) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE admin DROP FOREIGN KEY FK_880E0D76FE6E88D7');
        $this->addSql('ALTER TABLE admin DROP FOREIGN KEY FK_880E0D76FE6E88D7');
        $this->addSql('ALTER TABLE admin ADD CONSTRAINT `User` FOREIGN KEY (idUser) REFERENCES user (idUser) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_880e0d76fe6e88d7 ON admin');
        $this->addSql('CREATE INDEX User ON admin (idUser)');
        $this->addSql('ALTER TABLE admin ADD CONSTRAINT FK_880E0D76FE6E88D7 FOREIGN KEY (idUser) REFERENCES `user` (idUser) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC18545BDF5');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC18545BDF5');
        $this->addSql('ALTER TABLE application MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE application CHANGE status status LONGTEXT NOT NULL, CHANGE cover_letter cover_letter VARCHAR(255) NOT NULL, CHANGE applied_at applied_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE id idApplication INT AUTO_INCREMENT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idApplication)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT `fk_application_freelancer` FOREIGN KEY (freelancer_id) REFERENCES freelancer (idFreelancer) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT `fk_application_project` FOREIGN KEY (project_id) REFERENCES project (idProject) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX fk_application_project ON application (project_id)');
        $this->addSql('DROP INDEX idx_a45bddc18545bdf5 ON application');
        $this->addSql('CREATE INDEX fk_application_freelancer ON application (freelancer_id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC18545BDF5 FOREIGN KEY (freelancer_id) REFERENCES freelancer (idFreelancer)');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C74404555FD86D04');
        $this->addSql('DROP INDEX UNIQ_C74404554FBF094F ON client');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C74404555FD86D04');
        $this->addSql('ALTER TABLE client ADD industry VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT `fk_client_user` FOREIGN KEY (userID) REFERENCES user (idUser) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_c74404555fd86d04 ON client');
        $this->addSql('CREATE INDEX UserID ON client (userID)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C74404555FD86D04 FOREIGN KEY (userID) REFERENCES `user` (idUser) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY FK_E98F285991B5BE79');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY FK_E98F2859A455ACCF');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY FK_E98F2859CEDACF02');
        $this->addSql('DROP INDEX IDX_E98F285991B5BE79 ON contract');
        $this->addSql('DROP INDEX IDX_E98F2859A455ACCF ON contract');
        $this->addSql('DROP INDEX IDX_E98F2859CEDACF02 ON contract');
        $this->addSql('ALTER TABLE contract ADD projectID INT NOT NULL, ADD PaymentID INT NOT NULL, ADD ClientID INT NOT NULL, ADD Type VARCHAR(100) NOT NULL, ADD templateID INT DEFAULT NULL, ADD freelancerID INT DEFAULT NULL, ADD clientSignatureDate DATETIME DEFAULT NULL, ADD freelancerSignatureDate DATETIME DEFAULT NULL, DROP title, DROP content, DROP clientSignature, DROP clientSignatureImage, DROP freelancerSignature, DROP freelancerSignatureImage, DROP createdAt, DROP updatedAt, DROP idContractTemplate, DROP idClient, DROP idFreelancer, CHANGE amount amount DOUBLE PRECISION NOT NULL, CHANGE startDate startDate DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE endDate EndDate DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE status status TINYINT NOT NULL');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT `contract_ibfk_1` FOREIGN KEY (templateID) REFERENCES contract (idContract) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT `fk_contract_freelancer` FOREIGN KEY (freelancerID) REFERENCES freelancer (idFreelancer) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT `fk_contract_template` FOREIGN KEY (templateID) REFERENCES contract_template (idTemplate) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT `idClient` FOREIGN KEY (ClientID) REFERENCES client (idClient) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT `idPayment` FOREIGN KEY (PaymentID) REFERENCES payment (idPayment) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT `id_project` FOREIGN KEY (projectID) REFERENCES project (idProject) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX fk_contract_freelancer ON contract (freelancerID)');
        $this->addSql('CREATE INDEX idClient ON contract (ClientID)');
        $this->addSql('CREATE INDEX fk_contract_template ON contract (templateID)');
        $this->addSql('CREATE INDEX idPayment ON contract (PaymentID)');
        $this->addSql('CREATE INDEX id_project ON contract (projectID)');
        $this->addSql('ALTER TABLE contract_template MODIFY idContractTemplate INT NOT NULL');
        $this->addSql('ALTER TABLE contract_template ADD createdDate DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, ADD updatedDate DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, DROP contractType, DROP createdAt, DROP updatedAt, CHANGE description description TEXT DEFAULT NULL, CHANGE idContractTemplate idTemplate INT AUTO_INCREMENT NOT NULL, CHANGE title templateName VARCHAR(255) NOT NULL, CHANGE content templateContent LONGTEXT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idTemplate)');
        $this->addSql('CREATE UNIQUE INDEX templateName ON contract_template (templateName)');
        $this->addSql('CREATE INDEX idx_templateName ON contract_template (templateName)');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A57543575BE2');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A5757C954B00');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A57543575BE2');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A5757C954B00');
        $this->addSql('ALTER TABLE evaluation MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE evaluation CHANGE project_id project_id INT NOT NULL, CHANGE comment comment VARCHAR(255) NOT NULL, CHANGE type type LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE id idEvaluation INT AUTO_INCREMENT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (idEvaluation)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT `fk_evaluated` FOREIGN KEY (evaluated_id) REFERENCES user (idUser) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT `fk_evaluator` FOREIGN KEY (evaluator_id) REFERENCES user (idUser) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT `fk_project` FOREIGN KEY (project_id) REFERENCES project (idProject) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX fk_project ON evaluation (project_id)');
        $this->addSql('DROP INDEX idx_1323a5757c954b00 ON evaluation');
        $this->addSql('CREATE INDEX fk_evaluated ON evaluation (evaluated_id)');
        $this->addSql('DROP INDEX idx_1323a57543575be2 ON evaluation');
        $this->addSql('CREATE INDEX fk_evaluator ON evaluation (evaluator_id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A57543575BE2 FOREIGN KEY (evaluator_id) REFERENCES `user` (idUser)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A5757C954B00 FOREIGN KEY (evaluated_id) REFERENCES `user` (idUser)');
        $this->addSql('ALTER TABLE freelancer DROP FOREIGN KEY FK_4C2ED1E8FE6E88D7');
        $this->addSql('ALTER TABLE freelancer DROP FOREIGN KEY FK_4C2ED1E8FE6E88D7');
        $this->addSql('ALTER TABLE freelancer ADD idApplication INT DEFAULT 1, ADD idPortfolio INT DEFAULT NULL, CHANGE skills skills VARCHAR(255) NOT NULL COLLATE `utf8mb4_bin`, CHANGE verificationStatus verificationStatus LONGTEXT NOT NULL, CHANGE status status LONGTEXT NOT NULL, CHANGE idTask idTask INT DEFAULT 1');
        $this->addSql('ALTER TABLE freelancer ADD CONSTRAINT `fk_freelancer_portfolio` FOREIGN KEY (idPortfolio) REFERENCES portfolio (idPortfolio) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE freelancer ADD CONSTRAINT `fk_freelancer_task` FOREIGN KEY (idTask) REFERENCES task (idTask) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX PortfolioID ON freelancer (idPortfolio)');
        $this->addSql('CREATE INDEX ApplicationID ON freelancer (idApplication)');
        $this->addSql('CREATE INDEX TaskID ON freelancer (idTask)');
        $this->addSql('DROP INDEX idx_4c2ed1e8fe6e88d7 ON freelancer');
        $this->addSql('CREATE INDEX UserID ON freelancer (idUser)');
        $this->addSql('ALTER TABLE freelancer ADD CONSTRAINT FK_4C2ED1E8FE6E88D7 FOREIGN KEY (idUser) REFERENCES `user` (idUser) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE freelancer_forum_comment CHANGE post_id post_id INT DEFAULT NULL, CHANGE comment_text comment_text TEXT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE freelancer_forum_comment ADD CONSTRAINT `freelancerID` FOREIGN KEY (freelancer_id) REFERENCES freelancer (idFreelancer) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE freelancer_forum_comment ADD CONSTRAINT `postID` FOREIGN KEY (post_id) REFERENCES freelancer_forum_post (post_id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX postID ON freelancer_forum_comment (post_id)');
        $this->addSql('CREATE INDEX freelancerID ON freelancer_forum_comment (freelancer_id)');
        $this->addSql('ALTER TABLE freelancer_forum_post DROP gif_url, DROP category, CHANGE content content TEXT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL, CHANGE views views INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE freelancer_forum_post ADD CONSTRAINT `freelancerPOST` FOREIGN KEY (freelancer_id) REFERENCES freelancer (idFreelancer) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX freelancerPOST ON freelancer_forum_post (freelancer_id)');
        $this->addSql('DROP INDEX user_post_unique ON freelancer_forum_reaction');
        $this->addSql('ALTER TABLE freelancer_forum_reaction CHANGE reaction_type reaction_type VARCHAR(20) DEFAULT \'LIKE\' NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE freelancer_forum_reaction ADD CONSTRAINT `freelancerREACT` FOREIGN KEY (freelancer_id) REFERENCES freelancer (idFreelancer) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE freelancer_forum_reaction ADD CONSTRAINT `postREACT` FOREIGN KEY (post_id) REFERENCES freelancer_forum_post (post_id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX freelancerREACT ON freelancer_forum_reaction (freelancer_id)');
        $this->addSql('CREATE INDEX postREACT ON freelancer_forum_reaction (post_id)');
        $this->addSql('ALTER TABLE portfolio DROP FOREIGN KEY FK_A9ED10624DCE947A');
        $this->addSql('ALTER TABLE portfolio DROP FOREIGN KEY FK_A9ED10624DCE947A');
        $this->addSql('ALTER TABLE portfolio CHANGE created_At created_At DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE portfolio ADD CONSTRAINT `fk_portfolio_freelancer` FOREIGN KEY (freelancerId) REFERENCES freelancer (idFreelancer) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_a9ed10624dce947a ON portfolio');
        $this->addSql('CREATE INDEX freelancer ON portfolio (freelancerId)');
        $this->addSql('ALTER TABLE portfolio ADD CONSTRAINT FK_A9ED10624DCE947A FOREIGN KEY (freelancerId) REFERENCES freelancer (idFreelancer) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE portfolioitem DROP FOREIGN KEY FK_D6C82F0B55073B34');
        $this->addSql('ALTER TABLE portfolioitem DROP FOREIGN KEY FK_D6C82F0B55073B34');
        $this->addSql('ALTER TABLE portfolioitem CHANGE title title VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(255) NOT NULL, CHANGE technologies technologies JSON NOT NULL, CHANGE imageUrl imageUrl VARCHAR(255) NOT NULL, CHANGE projectUrl projectUrl VARCHAR(255) NOT NULL, CHANGE githubUrl githubUrl VARCHAR(255) NOT NULL, CHANGE created_At created_At DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE portfolioitem ADD CONSTRAINT `fk_portfolioitem_portfolio` FOREIGN KEY (idPortfolio) REFERENCES portfolio (idPortfolio) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_d6c82f0b55073b34 ON portfolioitem');
        $this->addSql('CREATE INDEX Portfolio ON portfolioitem (idPortfolio)');
        $this->addSql('ALTER TABLE portfolioitem ADD CONSTRAINT FK_D6C82F0B55073B34 FOREIGN KEY (idPortfolio) REFERENCES portfolio (idPortfolio) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE2804AB20');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE76A0B4B2');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE86AA1810');
        $this->addSql('DROP INDEX IDX_2FB3D0EE76A0B4B2 ON project');
        $this->addSql('DROP INDEX IDX_2FB3D0EE86AA1810 ON project');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE2804AB20');
        $this->addSql('ALTER TABLE project DROP freelancerIDD, CHANGE status status LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT `id_client` FOREIGN KEY (ClientID) REFERENCES client (idClient) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_2fb3d0ee2804ab20 ON project');
        $this->addSql('CREATE INDEX id_client ON project (ClientID)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE2804AB20 FOREIGN KEY (ClientID) REFERENCES client (idClient)');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB253F0ABB1C');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB253F0ABB1C');
        $this->addSql('ALTER TABLE task CHANGE deadline deadline DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE TaskStatus TaskStatus LONGTEXT NOT NULL, CHANGE dateAssign dateAssign DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE priority priority LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT `task_ibfk_1` FOREIGN KEY (idProject) REFERENCES project (idProject) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_527edb253f0abb1c ON task');
        $this->addSql('CREATE INDEX ProjectID ON task (idProject)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB253F0ABB1C FOREIGN KEY (idProject) REFERENCES project (idProject)');
        $this->addSql('DROP INDEX UNIQ_8D93D649E7927C74 ON `user`');
    }
}
