# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profiles'
    cv_directory: '%kernel.project_dir%/public/uploads/cv'
    student_cards_directory: '%kernel.project_dir%/public/uploads/student_cards'    
    tesseract_executable_path: 'D:\Program Files\Tesseract-OCR\tesseract.exe'
    ghostscript_executable_path: 'D:\Program Files\gs\gs10.07.0\bin\gswin64c.exe'
    tessdata_path: '%kernel.project_dir%/tessdata'
    openrouter_api_key: '%env(OPENROUTER_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\users\user\AvatarService:
        arguments:
            $profilesDirectory: '%profile_pictures_directory%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
